# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Nikolaos Pantelaios
tagline:          'My personal Website'
description:      'My personal Website'
url:              ''
baseurl:          /

author:
  name:           'Nikolaos Pantelaios'
  url:            ''

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           ''

  # Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "/img/theTest1.png"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache  