# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://npantelaios.github.io
baseurl:          ''

author:
  name:           'Nikolaos Pantelaios'
  url:            https://twitter.com/PantelaiosNikos

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/npantelaios/npantelaios.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache  
